### ISSUE TITLE
Exception starting Zatsu with Flask v3.0.0

### ISSUE THREAD

**Issue by AndrioCelos** [doxy-ai/ZatsuViewer#2]
It seems that the app currently is not compatible with the current version of Flask. The following exception occured when trying to start Zatsu:

```
Traceback (most recent call last):
  File "D:\Users\Andrea\Downloads\ZatsuViewer-master\zatsu.py", line 12, in <module>
    from api import _singletonApp
  File "D:\Users\Andrea\Downloads\ZatsuViewer-master\api.py", line 4, in <module>
    from app import App
  File "D:\Users\Andrea\Downloads\ZatsuViewer-master\app.py", line 32, in <module>
    from message import Message
  File "D:\Users\Andrea\Downloads\ZatsuViewer-master\message.py", line 4, in <module>
    from flask import escape
ImportError: cannot import name 'escape' from 'flask' (C:\Users\Andrea\AppData\Roaming\Python\Python312\site-packages\flask\__init__.py)
```

As a workaround, it's possible to install a previous version with `pip install flask==2.3.3`.

**Comment by AndrioCelos** [comment]
This seems to be a duplicate of an issue reported on Discord.

**Comment by doxy-ai** [comment]
This discord answer fixes it yes?
